# Generated by Django 4.1.1 on 2022-09-27 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='image',
            field=models.ImageField(default='no image', upload_to='main_app/static/uploads'),
        ),
    ]
