# Generated by Django 4.1.1 on 2022-10-03 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_book_image_quote'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quote',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='quote',
            name='date',
        ),
        migrations.AddField(
            model_name='quote',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='null'),
            preserve_default=False,
        ),
    ]
